### ISSUE TITLE
Some entity prototypes have components added or modified during initialization.  

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#10595]
This is a partial list of entity prototypes that need to be updated (though in some instances, the system/component itself may need to be fixed). There are several more not on this list, but those should get fixed by #10274. Currently the test added in #10274 just explicitly ignores the prototypes on this list.

A brute force way to figure out how to correct some of these prototypes is to just spawn them into an empty uninitialized map, saving the map, and then reading the map yaml.

- [x] Several weapons/staffs modify the BasicEntityAmmoProvider's  count field (#12385)
	- [X] WeaponProtoKineticAccelerator
	- [X] various WeaponStaff..... prototypes
	- [X] various WeaponWand..... prototypes
- [X] GlowstickBase modifies component on spawn: Item. Modified fields: heldPrefix  (#12385)
- [x] Thruster modifies component on spawn: AmbientSound. Modified fields: enabled
- [x] Gyroscope modifies component on spawn: AmbientSound. Modified fields: enabled
- [X] RemoteSignaller gains a component on spawn: SignalTransmitter (#12390)
- [x] A bunch of entities gain ContainerContainer on spawn: (#12390)
  - [x] filingCabinet, filingCabinetTall, filingCabinetDrawer
  - [x] WeaponLauncherChinaLake, WeaponLauncherRocket, WeaponLauncherMultipleRocket
  - [x] WeaponImprovisedPneumaticCannon
  - [x] MagazinePistolSubMachineGunTopMounted
  - [x] ClusterBang 
  - [x] LauncherCreamPie
  - [x] Crematorium
  - [x] LightReplacer 
  - [x] PortableScrubber 
  - [x] DisposalHolder
  - [x] AMEController
  - [x] JanitorialTrolley
  - [x] Vaccinator 
  - [x] ClothingHeadHatChef 
  - [x] CloningPod
  - [x] MachineFrame
  - [x] MedicalScanner
  - [x] KitchenMicrowave (#10766)
- [x] MultipleTools (JawsOfLife, SyndicateJawsOfLife, PowerDrill, Omnitool) modifies component on spawn: Tool. Modified fields: useSound
- [x] PortableScrubber modifies component on spawn: Physics. Modified fields: canCollide
- [x] ParticleAcceleratorControlBox modifies component on spawn: ApcPowerReceiver. Modified fields: powerLoad
- [x] Atmos devices enable themselves on init?
  - [x] GasPressurePump modifies component on spawn: GasPressurePump. Modified fields: enabled
  - [x] GasVolumePump modifies component on spawn: GasVolumePump. Modified fields: enabled
  - [x] GasFilter modifies component on spawn: GasFilter. Modified fields: enabled
  - [x] GasMixer modifies component on spawn: GasMixer. Modified fields: enabled
- [x] HospitalCurtainsOpen modifies component on spawn: Physics. Modified fields: canCollide
- [x] CargoPallet modifies component on spawn: Physics. Modified fields: canCollide
- [x] ParticlesProjectile modifies component on spawn: Fixtures. Modified fields: fixtures
- [x] FloorDrain gains a component on spawn: Fixtures
- [X] Organs modify solutions or add a solution container manager component: (#12390)
  - [X] OrganHumanLungs modifies component on spawn: SolutionContainerManager. Modified fields: solutions
  - [X] OrganRatLungs modifies component on spawn: SolutionContainerManager. Modified fields: solutions
  - [X] SentientSlimeCore gains a component on spawn: SolutionContainerManager
  - [X] OrganSlimeLungs modifies component on spawn: SolutionContainerManager. Modified fields: solutions
  - [X] OrganVoxLungs modifies component on spawn: SolutionContainerManager. Modified fields: solutions
  - [X] OrganAnimalLungs gains a component on spawn: SolutionContainerManager
- [x] Floodlight modifies component on spawn: Physics. Modified fields: canCollide
- [x] HolosignWetFloor gains a component on spawn: Fixtures
- [ ] HeadSkeleton modifies component on spawn: Vocal. Modified fields: action
- [x] DeployableBarrier modifies component on spawn: Physics. Modified fields: bodyType
- [ ] CrateArtifactContainer modifies component on spawn: PlaceableSurface. Modified fields: isPlaceable
- [x] A bunch of prototypes modify the tag component (be careful not to override inherited tags) (#12390)
  - [x] EmergencyMedipen
  - [x] AntiPoisonMedipen
  - [x] SpaceMedipen
  - [x] SprayBottle
  - [x] DrinkColaCan
  - [x] EpinephrineChemistryBottle
  - [x] RobustHarvestChemistryBottle
  - [x] NocturineChemistryBottle
  - [x] EphedrineChemistryBottle
  - [x] OmnizineChemistryBottle
- [x] MachineFrame modifies component on spawn: Construction. Modified fields: defaultTarget
- [x] GravityGenerator (Maybe this should actually just be an ignored prototype?)
  - [x] modifies component on spawn: AmbientSound. Modified fields: enabled
  - [x] modifies component on spawn: ApcPowerReceiver. Modified fields: powerLoad
  - [x] modifies component on spawn: PointLight. Modified fields: radius
  - [x] modifies component on spawn: AmbientSound. Modified fields: enabled
  - [x] modifies component on spawn: ApcPowerReceiver. Modified fields: powerLoad
  - [x] modifies component on spawn: PointLight. Modified fields: radius
- [x] the various lathe entities modify `materialWhiteList` on spawn (#11201)
- [x] All the beakers, MopBucket, JanitorialTrolley, Bucket all modify the drink component solution on spawn (#2390)
- [x] Various doors & airlocks modify fixtures on spawn:
  - AirlockShuttle, AirlockGlassShuttle, AirlockExternalShuttleLocked, AirlockExternalGlassShuttleLocked, AirlockExternalGlassShuttleLocked, AirlockExternalGlassShuttleLocked, AirlockExternalGlassShuttleEmergencyLocked
- [x] Machine Linking (#11108):
  - [x] CloningPod gains a component on spawn: SignalReceiver
  - [x] C4 modifies component on spawn: SignalReceiver. Modified fields: inputs
  - [x] Poweredlight & inheritors gains a component on spawn: SignalReceiver
  - [x] ComputerCloningConsole modifies component on spawn: SignalTransmitter. Modified fields: outputs
  - [X] GasDualPortVentPump gains a component on spawn: SignalReceiver
  - [X] Recycler gains a component on spawn: SignalReceiver
  - [X] CargoTelepad gains a component on spawn: SignalReceiver
  - [X] ConveyorBelt gains a component on spawn: SignalReceiver
  - [X] MedicalScanner gains a component on spawn: SignalReceiver
- [x] A bunch of prototypes gain a tag component: (#11087)
  - [x] FoodBowlBig
  - [x] FoodBowlFancy
  - [x] FoodCondimentPacket
  - [x] FoodCondimentBottle
  - [x] FoodCondimentBottleSmall
  - [x] Syringe
- [x] Recycler modifies component on spawn: Fixtures. Modified fields: fixtures (#11108)
- [x] some ClothingHeadHatHardhat base entity adds item slots & containers on spawn (#11087)
- [x] CargoTelepad modifies component on spawn: Physics. Modified fields: canCollide (#11108)
- [x] ConveyorBelt modifies component on spawn: Fixtures. Modified fields: fixtures (#11108)
- [x] flashlight related (#11087)
  - [x] ClothingHeadHelmetFire modifies component on spawn: Clothing. Modified fields: equippedPrefix
  - [x] ClothingHeadHelmetFire modifies component on spawn: Item. Modified fields: heldPrefix
  - [x] ClothingHeadHelmetAtmosFire modifies component on spawn: Clothing. Modified fields: equippedPrefix
  - [x] ClothingHeadHelmetAtmosFire modifies component on spawn: Item. Modified fields: heldPrefix
- [x] CableTerminal gains a component on spawn: CollideOnAnchor (#11087)
- [ ] A bunch of fixture-less entities set can-collide to false on init. For a list, just look at the test ignore list

**Comment by EmoGarbage404** [comment]
kitchenmicrowave fixed by #10766

**Comment by EmoGarbage404** [comment]
the lathes were fixed with lathe ECS

**Comment by rolfero** [comment]
"All the beakers, MopBucket, JanitorialTrolley, Bucket all modify the drink component solution on spawn" was also fixed in #12390
