### ISSUE TITLE
Features priority?

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#14]
# Welcome to content club
Remember Urist's roadmap? **THIS IS IT NOW, FEEL OLD YET?**
Well, I guess it's time to organize content development in the same fashion we did so for engine's one! First we need to decide priority of features so we might create first milestone and have an actual roadmap. Below is Urist's original priority list. Feel free to suggest your options!

## Top priority (so the first milestone)
1. [x] UI (prototype - everything following will be added to the UI as it comes; but should be at least in general planned out beforehand) - https://github.com/space-wizards/space-station-14/pull/463
2. [x] Containers
3. [x] Player to entity interaction - #9 
4. [x] Holding and dropping items
5. [x] Damageable entities - #10
6. [x] Melee weapons
7. [x] Basic inventory (toolbelt, backpack, equippable items) - #8
8. [x] Health and stamina (non-organ based for now; will need to update it once those systems are designed) - #10

## Other priority (second milestone)
1. Power system - #6, #25 
2. ID system - #31 
3. Remote control, signal sending - #30 
4. Construction/destruction of snap grid elements
5. Temperature
6. Substances (non-discrete liquids/gasses/solids)
7. Atmos (gods this will be a doozie) (requires 5 and probably 4)
8. Ranged weapons
9. Chat system
10. Combat in general
11. Grabbing and dragging
12. Examine functionality
13. Organs
14. Basic game mode
15. Basic events

## Low priority and ongoing (several milestones for later)
1. Chemicals
2. Hacking
3. AI
4. Logic computing?
5. Robutts?
6. Science + how plasma works - #29 
7. Medical
8. Gravity
9. Do we even need intents?
10. Jobs
11. Radios or lack thereof :)
12. PDA functions
13. Admin tools
14. Events
15. Modes
16. Cookin with bob
17. Screw mining but gotta consider it anyway
18. Botany
19. Space fauna/critters (monkeys, space slugs)
20. Heck yeah security I love it
21. But that is part of the jobs
22. Eh fuck it might as well keep a separate point open
23. Not like I answer to anyone
24. Livin on the edge
25. i need sleep
26. Grabbing
27. Construction/destruction as in the game system
28. Space, gravity, antigravity and so on
29. Disease
30. After-round metrics and statistics
31. Janitor the garbage man
32. Blood and other substances on the floor
33. Cameras
34. Grenades, bomb assembly (and assembly in general?)
35. Gravity
36. Engines
37. Scoring is yes
38. Viruses aw ye
39. Server hub, player profile, databases, trust
40. Vent shafts?
41. Monkeys!
42. Bots (beepsky and such)

**Comment by outbools** [comment]
So Top Priority + Power system(since cluster already making it) sounds good for first milestone:
have something to pick up, drop and punch.

**Comment by Silvertorch5** [comment]
Cowrp is highest priority.

**Comment by outbools** [comment]
@Silvertorch5 set up cowrp waffle and create cowrp milestone

**Comment by outbools** [comment]
if you make a milestone you don't need to check checkboxes because AUTOMATION
also waffle when

**Comment by Silvertorch5** [comment]
https://waffle.io/space-wizards/space-station-14-content

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/hqouCZ8WSaODYXh5L_WuUA?both#Urist-2017-10-24) (link will likely break soon, temp location)

**Comment by Carolyn3114** [comment]
o7

**Comment by ZoldorfTheWizard** [comment]
o7
