### ISSUE TITLE
Replay related issues & tasks

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#17170]
This is just a collection of replay related issues and tasks. Some of these are engine issues.

## Bugs:
- [ ] There is an appearance bug that shows up in the video in space-wizards/RobustToolbox/pull/4122. Though it might get fixed before that PR is merged.
- [ ] Missing audio & popups. Some audio and popups are currently not recorded because they use obsoleted methods. All uses of the obsolete methods just need to be removed updated to use the new methods.
- [ ] Find all the missing bugs (AKA replays actually need testing with real rounds).

## TODO / Features

- [ ] Allow observers to override eye rotation & zoom while spectating entities. 
- [ ] Better time control widget
  - Hold down fast forward button.
  - Some editable field for jumping to a specific timestamp
  - Fancier slider with finer control for long replays.
  - Custom Chat UI. Currently it is very hacky and just disables text-input.
  - "OldChat" layout.
- [ ] Viewable BUIs (aka: refactor BUIs to use component states)
- [ ] Record some server-side data and make it viewable in a replay (e.g. pipenet & powernet stats) 
- [ ] Better UI
  - Timeline viewer for players (e.g., make it easy to jump to a point where a player died).
  -  Admin tattle/warning viewer.
  - Teleport-to menus. These cannot just use the existing tpto command, because if the player is currently spectating an entity they need to first detach them and span a new spectator ghost.

### Automated recording & distribution
- [ ] Some kind of system that automatically starts & stops recordings as rounds start & stop,
- [ ] Add support for the launcher to launch local/offline single-player games.
- [ ] Automated replay filtering/redaction tools
  - E.g., admin chats & ahelps should be recorded so that it can be seen in game during a replay while admins are reviewing a round, but they should not be viewable in replays made available to the general playerbase.
  - Even if we do decide to just make them all public, its probably still worth creating some tool that can read through and filter or preproces replays (e.g., see all the code comments about checkpoint state generation.
 
How exactly replays will be launched or distributed remains to be determined (aka when Julian or PJB code it).  Realistically, replays should probably be distributed in some way that makes it easy to automatically obtain the correct replay client that is required to read them. This was already discussed a bit [on discord](https://discord.com/channels/310555209753690112/900426319433728030/1112533386876174487).

**Comment by ElectroJr** [comment]
Anyone that has editing permissions should feel free to just add, modify or just re-organize the tasks.

**Comment by Errant-4** [comment]
Bug: At all times, all characters show the "blank/catatonic" description when examined
![Screenshot from 2023-12-11 22-39-26](https://github.com/space-wizards/space-station-14/assets/35878406/c31c03c8-0637-48d2-bd50-7a060fb599df)



Bug: After clicking on the timeline to jump time-position a few times, it will bug out and start "following" the mouse, quickly spooling the footage trying to follow the motion of the mouse. This is rather undesired/unintuitive behavior, and does not perform well replaying it either. This continues until it registers a click OUTSIDE the timeline bar.

https://github.com/space-wizards/space-station-14/assets/35878406/5f0444af-7dc5-41f9-8eaa-8f6a837efb92
