### ISSUE TITLE
Paramedic checklist

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22145]
## Description
Just some things I want to change
Feel free to do things for me

* [x] remove spare suit and clothes from the medical wardrobe machine #22146
* [x] rename their medical belt to EMT belt #22173
* [ ] make the EMT belt a unique prototype and give it a darker sprite
* [ ] change the suit to function like a hardsuit (like voidsuits do in baystation 12) but in return remove slash resistance, make it ginormous, and it won't get a built in flashlight
* [x] give them blue shoes and rollerbed in bag #22649
* [x] add the room and role to barratry #22150
* [x] add the room and role to marathon #22151

**Comment by JoeHammad1844** [comment]
nuh uh this shit aint finished, i got more to do

**Comment by Emisse** [comment]
it auto closed from your git comment

**Comment by UbaserB** [comment]
>baystation 12

**Comment by JoeHammad1844** [comment]
> > baystation 12

something wrong with space station 12? :trollface:

**Comment by JoeHammad1844** [comment]
i didnt even like the issue this time

**Comment by JoeHammad1844** [comment]
for some reason it wont let me reopen it myself, or I cant find the button

**Comment by ficcialfaint** [comment]
> i didnt even link the issue this time

![image](https://github.com/space-wizards/space-station-14/assets/46868845/226ff723-02f4-4028-8ad5-3eece0b4e7d4)

**Comment by JoeHammad1844** [comment]
damn

**Comment by JoeHammad1844** [comment]
thoughts on EMT belt sprite?
in gimp
![image](https://github.com/space-wizards/space-station-14/assets/130668733/7d05da4c-a4d5-4de2-a25f-48dada695f5a)
raw
![icon](https://github.com/space-wizards/space-station-14/assets/130668733/dcf794ea-b9aa-49bf-a1f7-045d0f2eed32)

**Comment by JoeHammad1844** [comment]
worn sprite
![image](https://github.com/space-wizards/space-station-14/assets/130668733/3b0c40c3-4e5a-4316-83ac-8662b81ac1eb)
