### ISSUE TITLE
Station Beacon/Map qol requests

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#23609]
- [X] Localise beacon labels Added by #24138
- [ ] Beacons should be able to be hidden from the Warp list
- [X] Map labels should scale with zoom level, ~~preferably adjustable per prototype, so "main" department labels could remain prominent and readable, while the ones for individual rooms/etc would shrink (MinSize and MaxSize and make it adjust linearly between those?)~~ Added by #23777
- [ ] Label font size to be adjustable by the player
- [ ] More granularity in what labels are shown (Per department? "My Department"? Main/Minor labels?)
- [ ] Beacons to be able to fill the room with a specified background color (Emo might already be working on this)
- [ ] Station map should show docked lifepods/shuttles/etc #22169
- [X] Station map does not have margins #15998
- [X] Map Label's background-box should be less transparent, or be adjustable by the client #23584
- [ ] Beacons to be able to display an image instead of text
- [ ] Label colors to be adjustable, possibly client-side. Or at least the wall color
- [ ] Larger/more important labels should always be rendered above smaller/less important labels when overlapping, or adjustable opacity of both text and background based on zoom level similar to MinSize MaxSize scaling
- [ ]  #23585

**Comment by iacore** [comment]
Can you add a white border to the sec text? Still can't see the sec text clearly (in  https://github.com/space-wizards/space-station-14/pull/23777).

**Comment by Errant-4** [comment]
> Can you add a white outline to the sec text? Still can't see the sec text clearly (in #23777).

That would need an engine update, the drawstring function does not currently do outlines. I would suggest zooming in the make the text larger

**Comment by iacore** [comment]
can you draw the text 8+1 times? 8 times in white with offset to 8 directions.

**Comment by Errant-4** [comment]
If/when I add further accessibility options to this it will either be customisable colors and backgrounds, or adjustable font size so you can make it larger without zooming in on the map. But someone else is welcome to code outlines if they want to give it a shot

**Comment by iacore** [comment]
Can I change the engine to add outlines?

**Comment by Errant-4** [comment]
> Can I change the engine to add outlines?

I don't know, can you?
(That is the actual answer. Can you? You are free to submit a PR adding new functionality to Robust Toolbox)

**Comment by lapatison** [comment]
Station beacon text localization, please

**Comment by Errant-4** [comment]
> Station beacon text localization, please

Oh, good point,! I planned to even do that already but bounced off, and then forgot to even put it on this list. Thanks!
