### ISSUE TITLE
Vox Checklist

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#26730]
todo

- [x] Displacement maps
- [x] Custom clothes that can't be displacement mapped
- [x] Loadouts 
- [x] A way to force N2 and mask on at spawn (species specific loadout locked items)
- [x] Oxy Tox Metabolism

**Comment by Errant-4** [comment]
#25083
 #26705

**Comment by TheShuEd** [comment]
#27407
2 bugs, need fix for Vox

**Comment by Plykiya** [comment]
other todos:
vox nukies DIE (no nukie loadouts??? force nukies to be humans?)
add vox to loadout options
