### ISSUE TITLE
Todo list for PipeNets

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#2810]
Things needed for a station atmos setup.
Assumes the minimal parts needed for a functional setup, not the things needed to clone SS13's setup.

Some parts are already done, but a few things, specifically `PipeNetDeviceComponent` may need to be refactored to improve code quality.

Basics:
- [x] Basic Pipes

Canisters:
- [x] Gas canisters
- [x] Gas canister ports
- [x] Gas canister port sprites & visualizer

Pumps:
- [x] Basic pumps
- [x] Gas filter
- [ ] Pump UIs

Station pressure maintenance:
- [x] Vents/Siphons
- [ ] Vent/Siphon UI controls (Air alarms not necessary right now, just make a simple UI for individual vents/siphons)

Temperature Control
- [ ] Magic gas heating/cooling unit
- [ ] A UI for it

Afterwards:
- [ ] A way for players to place/remove all atmos equipment
Could be handled with items, if we want to not create a new entity when placing/removing pipes/etc. some refactoring will need to be done.

**Comment by mirrorcult** [comment]
superseded by list in #3833
