### ISSUE TITLE
Guidebook content megaissue 

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#28615]
This is a collection of various issues & tasks related to missing guidebook content or instances where guidebooks should get used but currently aren't. For missing guidebook functionality or bugs see #17163

**Missing Guides**
- [ ] Tesla needs a guidebook #23112
- [ ] All antagonist roles should have a guidebook. Related to #28614
  - [ ] #22918 
- [ ] Ghost role prototypes should have guidebook entries.
- [ ] Combat needs a guidebook (#17530)
- [ ] Job icons / huds need a guidebook (#18548)
- [ ] All jobs should have a guidebook, in addition to the current department-level guidebooks. Related to #28614
  - [ ] Might need to add support for giving imbedded entities starting gear
- [ ] Department guides should list associated jobs

**Make more use of guidebooks**
- [ ] The rules window should probably be a guidebook #19763
- [ ] The Ghost role UI should link to guidebooks. Related to #20192. Should work somewhat like #28614.
- [ ] The character menu should probably use, link to, or be a guide entry of sorts.
  - [ ] Objectives should have guidebooks, or be some kind of guidebook control

**Comment by joelsgp** [comment]
I'd like to suggest the guidebook should do links better, like when you click a GuideEntityEmbed it should take you to that entity's guidebook page if it exists. 
For instance, The Network Configurator has its own book page, so when I click the embed on the Engineering page it should take me to info about the network configurator

**Comment by lzk228** [comment]
> * The rules window should probably be a guidebook

this one is definitely done

**Comment by JoeTheJanitor** [comment]
The ['food recipes' guidebook entry](https://github.com/space-wizards/space-station-14/blob/e438b8b25ff1d3ace656251044397648a3c6fcd5/Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml#L4) doesn't include '5u milk' as an ingredient in cake batter. 

I'm not sure if this is the right place to report typos and information errors in currently existing entries (it does say 'megaissue', so it seems reasonable)

**Comment by lzk228** [comment]
> The ['food recipes' guidebook entry](https://github.com/space-wizards/space-station-14/blob/e438b8b25ff1d3ace656251044397648a3c6fcd5/Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml#L4) doesn't include '5u milk' as an ingredient in cake batter.
> 
> I'm not sure if this is the right place to report typos and information errors in currently existing entries (it does say 'megaissue', so it seems reasonable)

food recipes should use guidebook generator in the same way as reagents

**Comment by iacore** [comment]
Maybe an issue for new players: Leviathan doesn't show the Guidebook on start. It shows the rules instead.
