### ISSUE TITLE
Asteroid Fauna Checklist

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#30767]
## Description
Our current fauna lacks any strong theming and is kind of just spammed everywhere. This is really bad for salvage, since they're working off-station a lot, and are going to immediately notice how weak it is.
Additionally, most of our mobs have no variety in how they function, making them uninteresting to fight.

Fortunately, as a baseline, SS13 is excellent for this, and has lots of good fauna intended for the situations we want them in already.
Goal: implement all of these.

[The TG wiki is decent reference for how these work mechanically,](https://tgstation13.org/wiki/Critters#Hostile) but I will elaborate on them more to be more clear.

- [ ] **Goliath**: Summons 4 tentacles in a cross shape under the player that stun them in place for about 2 or 3 seconds if they get caught. Chases the player and hits them with a strong melee attack.
![Goliath](https://github.com/user-attachments/assets/4ba69b6e-020d-448c-ab46-2aba35388d76)

- [ ] **Hivelord**: Summons several "brood" minions to swarm the player with. Broods die in one hit and do weak damage. Hivelords themsleves have a decent amount of HP.
![Hivelord](https://github.com/user-attachments/assets/848559e9-14ae-4d58-a99c-bfab4e400168)

- [ ] **Basilisk**: Has a low detection radius (about 3 tiles.) Slowly wanders around when not alerted. When alerted, it turns an angry red, fires ice beams at the player to slow them, then melees the player.
![Basilisk](https://github.com/user-attachments/assets/e803177e-4615-4f65-b380-40e48d94dbc9)

- [ ] **Goldgrub**: From the /tg/ wiki: "Mostly harmless and quite rare. Found on the asteroid, these creatures swallow up any loose, valuable ore they can find and flee when approached by a human, smashing through even solid rock on their path of escape before burrowing into the ground. "
![Goldgrub](https://github.com/user-attachments/assets/3587e7dd-4040-4503-9cae-8badee7b8574)

Hivelords are also *technically* included in this, since they are used in dungeons & ruins, but they're moreso planetmap creatures, so they'll be left to that issue.

**Comment by bruhmogus** [comment]
if we implement goldgrub definitely make sure it can only burrow into planetary tiles, because i know some mad son of a bitch is gonna use eight disablers to drag that mf onstation

**Comment by EmoGarbage404** [comment]
> if we implement goldgrub definitely make sure it can only burrow into planetary tiles, because i know some mad son of a bitch is gonna use eight disablers to drag that mf onstation

how are you gonna drag it away mf is gonna burrow into the ground

**Comment by Golinth** [comment]
> stun and cuff

Cuff what, it’s a worm

**Comment by deltanedas** [comment]
![image](https://github.com/user-attachments/assets/1713c577-4983-4935-adef-3d79f57f80b1)

**Comment by BolloTea** [comment]
Sorry, I just remembered one thing.  On Shiptest ss13, there were spawners on the asteroids in the form of tunnels that spawned certain monsters that needed to be destroyed.  They contained ore in decent quantities and random miner loot, of the type: medipen, crusher, drill, body or modules for the accelerator.  It was great to see this on some dungeons or large asteroids
