### ISSUE TITLE
Planet Fauna Checklist

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#30784]
## Description

Our current planetside fauna consists exclusively of xenos and carps, neither of which are a good fit for expeditions or any kind of planetary exploration. Additionally, it would be good to have unique fauna selections for each planet variant (grass/jungle, cave, lava, ice) so as to give them more stuff to distinguish them, as right now they feel a bit same-y.

Once these are implemented, carps should be relegated to solely space threats and xenos should be retired until the proper xenomorph antagonist is complete.

### Grassland/Jungle

- [ ] **Argocytes:** Complex ecosystem of various different alien creatures. These exist in the game's files but the balancing is a bit out of wack. These can serve as a drop-in replacement for xenos. There is a huge variety of these and they should realistically have unique behavior in the future. This is an "ask emisse" statement.
![leviathing](https://github.com/user-attachments/assets/716b8f19-9ac3-45aa-8c96-a728fa6cf51c)

### Cave

- [ ] **Spiders:** Has a basic implementation on-station. For planet-side mobs, should probably have some basic respawning or nest mechanic that interfaces with their webs. At the very least, it needs an update to the NPC logic to enable it to use web ability automatically.
![Guard](https://github.com/user-attachments/assets/2bfe7663-64b0-4ff3-91dc-1986e7ce303a)
![nurse_South_0](https://github.com/user-attachments/assets/1b0cba60-4ca9-4fd7-98dd-4e777656c1fc)
![hunter_South_0-1](https://github.com/user-attachments/assets/3afdd26f-1ae6-4036-b5ac-25035d84d90f)
![spiderling_South_0](https://github.com/user-attachments/assets/492bdb87-05d0-40b4-9086-78a05850b2da)

- [ ] **Space Ticks:** Should be rethemed into a more conventional bug creature. The asset exists however and they've always been an alright threat. Could serve as a decent thing to pad out the creatures in the Cave.
![icon](https://github.com/user-attachments/assets/0f480e9b-87f2-4624-a9da-8ce0585e960b)

- [ ] **Goldgrub:** See #30767. Could be spawned rarely around caves. 
![356094174-3587e7dd-4040-4503-9cae-8badee7b8574](https://github.com/user-attachments/assets/c288a136-8b7b-4697-ba1f-8e993f8c7806)

### Ice

- [ ] **Hivebot:** From /tg/ wiki: "A roaming bee-bot equipped with an attached weapon that fires bullet projectiles that can also come in stronger versions, its rate of fire is slow and is considered moderate in terms of damage. Easily destroyable, however this is countered by being in packs or even in an entire platoon."
![Hivebot](https://github.com/user-attachments/assets/41d46981-d831-4bb6-b266-bf08c11efae3)

- [ ] **Polar Bear:** Just a basic simplemob that can maul players. Should be decently strong and fast.
![polarbear_South_0](https://github.com/user-attachments/assets/609e71d3-3395-4fd5-b464-495dbf7301d7)

- [ ] **Wolves:** Roam in packs, attack different mobs, and are extremely fast. Bonus points if they howl to let you know that they are nearby. Could serve as a rare threat compared to the more frequent hivebots roaming the surface.
![wolf_South_0](https://github.com/user-attachments/assets/e379f173-bfb2-4211-8406-6948b25df3e8)

- [ ] **Watcher:** A prototype for this exists in code but it doesn't have it's cold attack. You get bonus points if i can reuse it for a temperature gun in the future. Also I'd ideally like a resprite but its not important.
![watcher_icewing_South_0](https://github.com/user-attachments/assets/5394b76b-ea5a-450b-96a1-8eb3e8f01416)

### Lava
- [ ] **Legion:** Decently strong mob that spawns small flying skulls that attack the player. The individual skulls are really weak but attack frequently whereas the main body doesn't attack much at all.
![legion_South_0-1](https://github.com/user-attachments/assets/17c77b17-cb19-48b5-a54a-67091c943a2b)

- [ ] **Watcher:** Same as the variant on the ice planet, except the projectiles raise body temperature instead of lowering it.
![watcher_South_0](https://github.com/user-attachments/assets/ec73e80c-7ab6-4fb9-9e9c-6155ed19f96f)

- [ ] **Goliath:** Largely the same as #30767. Some servers seem to have an alternate variant that spawns extra tentacles so that might be a good fit here to distinguish it from the asteroid mob.
![goliath2_South_0](https://github.com/user-attachments/assets/f37cde55-1235-494c-b706-0722b57d81ac)

- [ ] **Ashwalkers:** Primitive lizard people armed with gladiator gear and bone weapons. Would be good to spawn in small encampment just to make them more thematically interesting.
![Ashwalker](https://github.com/user-attachments/assets/122b6e25-cad4-4575-9fd3-03020fe1aa1c)

**Comment by BolloTea** [comment]
If I'm not mistaken, Goliath (Not ancient) also uses a dash
