### ISSUE TITLE
Icemoon Asset Checklist

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#30974]
## Description

Checklist for tracking all the various assets we need to get icemoon mapping and generation stuff off the ground.

### Tiles
- [ ] **Permafrost**: Basically the subfloor tile for icemoon. Pairs really fucking well with the snow tiles and all the edge smoothing there. The sprites additionally have a bunch of smoothed icons for some sort of path thing, but i think just having the base tile is fine.
![permafrost_full_South_0](https://github.com/user-attachments/assets/6be0add8-5e14-4108-9248-483b5874ac56)

- [ ] **Dark Ice**: Just a sprite-swap of our existing ice textures. This one from /vg/ has smoothing support so those should be ported with this. There's also another ice sprite that is quite a bit lighter and has no smoothing. That one might also be worth porting.
![ice1_South_0-1](https://github.com/user-attachments/assets/1135340d-390d-4a9b-a612-ad9d51b138d8)
![ice_South_0](https://github.com/user-attachments/assets/5a341929-fc94-460e-bb11-76e6dd927203)

- [ ] **Dug Snow** (Rename): "Dug Snow" exists in game but the name is kinda awful and I prefer the name "grave snow" that other servers use.

### Walls/Structures
- [ ] **Snow Structure Overlays**: Basic entity overlays that would be good for flavor in the future. These would ideally be hooked up to some kind of weather system or component logic (add snow overlay after being in snowy weather for X time) but if whoever adds them can't implement that, then i'll get to it myself.
![snowfloor_South_0](https://github.com/user-attachments/assets/2bb199fa-24a7-4c45-8554-14c8e1b1d4fd)
![snowairlock_South_0](https://github.com/user-attachments/assets/17b7eb23-5d62-4c2b-8e48-310974a54a36)
![snowwall_n_South_0](https://github.com/user-attachments/assets/880baa2b-1eef-49a8-809f-82f10c6251c0)

- [ ] **Rock Variants**: Some more colorful variants of the traditional white snow rock. These don't necessarily need to support ores although it would be nice if they did (in a way that didn't bloat the fuck out of the yaml)
![snow_rock_South_0](https://github.com/user-attachments/assets/2c6f9f05-9a86-4d63-a95b-d479c42d3050)
 ![icerock_South_0](https://github.com/user-attachments/assets/31d6eeae-9702-4821-9787-ee8afe5138c5)

- [ ] **Wood Wall/Door** (Resprite): We have already existing wooden doors and walls but they don't match the general art style or each other really well. They both would likely need a resprite to work a bit better in the environment.

### Mobs
Includes extended assets for some things mentioned in #30784.

- [ ] **Hivebots**: Having some different variants of melee v ranged for hivebots could be good. Additionally, some kind of centralized fabricator that you have to shut off could also be really cool. I don't forsee these guys having any loot, but any structures associated with them should definitely have some stuff to sell.
![356256837-41d46981-d831-4bb6-b266-bf08c11efae3](https://github.com/user-attachments/assets/ccdc6939-252c-47cd-8fa2-d89cfac058a0)

- [ ] **Polar Bear**: Doesn't need to be anything other than a decently tanky melee mob. The pelt should be wearable and sellable for a fat chunk of change, though.
![356257468-609e71d3-3395-4fd5-b464-495dbf7301d7](https://github.com/user-attachments/assets/6d7d2099-ee0f-4f4a-8c79-7826bd018e5a)

- [ ] **Wolves:** Same as the bears. These will get their own AI but all that's really needed asset-wise is the sellable pelts.
![356259174-e379f173-bfb2-4211-8406-6948b25df3e8](https://github.com/user-attachments/assets/f8c1eff6-4210-4394-a6ae-f0717a381640)

- [ ] **Deer**: These should definitely have some custom evasive AI for running from players, but its still a lot of the same. Have some leather, antlers, and potentially even a wallmount head if you want to go crazy with it. These are basically just the goldgrubs of the icemoon and should be equally as lucrative.
![deer_South_0](https://github.com/user-attachments/assets/65021f0d-2133-4dd6-a8bc-4ecd3957c786)

- [ ] **Wooly Goat**: A less flighty version of the deer. Should still have some drops (fur, horns) but when you attack it, it should try and fight back.
![woolygoat_South_0](https://github.com/user-attachments/assets/8f2aedc2-719c-4e38-855b-e12648e91434)

### Clothing

**TBD**: Eventually we'll probably want some outfits for populating ruins and corpses but the style is yet to be determined.

### Plants

**TBD**: Beyond the basic trees and ground decals we have, we will probably also want some kind of botany plants that you can scavenge and grow. what these look like and their properties haven't been decided on yet.

**Comment by EmoGarbage404** [comment]
upcoming planet thing being worked on. It's part of the larger salvage rework.

**Comment by lzk228** [comment]
> * Should still have some drops (fur, horns)

can we make horns like in minecraft? :trollface:

**Comment by EmoGarbage404** [comment]
> can we make horns like in minecraft?

yeah that'd be cool af. get a didgeridoo soundfont or something and slap it on there.

**Comment by Strol20** [comment]
I think the weather room logic needs to be added. As far as I know, weather effects just appear on land tiles, ignoring other tiles.
