### ISSUE TITLE
Admin Features issue collection

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3684]
Opening a collection issue for all features required for proper adminning & putting this on prio 1 since we are growing pop

## Essential
- Show player roles in admin menu (#3494)
Could also maybe do a toggleable admin-overlay that shows player roles above their heads/ maybe some more info?
- Player warp options are broken (#3393)
- Adminlogs (#3178)
- Adminhelps (#1587) (#3230)
should have reply & teleport to 

## Non-Essential
- Interaction w/ map, AI-Style (#3230)
- AI tooling (#3205)

**Comment by Peptide90** [comment]
IMO #3205 should be consolidated under this. Have a section for admin tools / commands, admin features and player menu tools?

### Player Menu Related

- [ ] #5461 ahelps should show character name and online status (hover over for disconnect forced or connection issue? might be too far)
- [ ] #5294 job bans, opening more job slots? (Sort of a HoP thing) + assign traitor or assign random traitor.
- [ ] #4792 player note system - leave notes for other admins, maybe even a visual icon that a player has a warning. Warning, kick and ban history, interface for seeing job bans?

### Admin Tools / Commands

- [ ] Disable OOC for X time
- [ ] Freeze player
- [ ] Give item commands? Might be unnecessary but more discrete than placing entities
- [ ] Inspect atmos at tile (hover over to see atmos stats like temp, pressure and main gas component?)
- [ ] Better admin logs - Yeah it's great having a massive library of stuff but I'd like the classic admin notification in chat "big explosion at X by Y, teleport to?" and X killed Y so I don't need to filter loads of stuff to get a log or decipher what pressure release was the bad one.

**Comment by ShadowCommander** [comment]
- [ ] Basic chat filter that will notify game admins to make banning easier.
- [ ] Verbs for all admin tools in the new admin verb category.
- [ ] Rules popup when a player connects to the game.
  - [ ] Minimum time before they can close it.

**Comment by Efruit** [comment]
wrt. player notes (#4792) - I know it's a feature from SS13, but doesn't it seem a bit odd that it'd be implemented in-game? It seems like one of those things that a server host would run separately, like Grafana and Loki.

**Comment by Peptide90** [comment]
> wrt. player notes (#4792) - I know it's a feature from SS13, but doesn't it seem a bit odd that it'd be implemented in-game? It seems like one of those things that a server host would run separately, like Grafana and Loki.

Imo, I don't want to have to open lots of windows outside the game to admin a round. I should be able to right click a player and see their notes in a click and make a decision there and then. But I do see your point.

**Comment by PaulRitter** [comment]
> wrt. player notes (#4792) - I know it's a feature from SS13, but doesn't it seem a bit odd that it'd be implemented in-game? It seems like one of those things that a server host would run separately, like Grafana and Loki.

player notes will be backed by a database if thats what you mean. they'd be accessible ingame, was well as maybe over a webpanel, as we do with bans rn.

**Comment by Efruit** [comment]
I meant that notes seem like something that ought to be a discrete system or application, not a part of the game. Kind of like how we have forums as its own site, not built in to the game itself.

**Comment by PaulRitter** [comment]
> I meant that notes seem like something that ought to be a discrete system or application, not a part of the game. Kind of like how we have forums as its own site, not built in to the game itself.

still dont get what you mean? this would be the forum-equivalent of displaying forum posts ingame. the application is located elsewhere, more specifically: its just being a database. Modifications are written to it either from ingame or a web panel.

**Comment by Efruit** [comment]
> this would be the forum-equivalent of displaying forum posts ingame.

Yes, exactly. I would be concerned if someone proposed doing that. I'm similarly concerned about this.

> Notes need to be easily accessible ingame, period. You'll want to click on a player to quickly see their notes and not have to copy their uname/id around multiple applications

True, but I'd feel better if it were a button that opened the right URL in the user's preferred browser (or CEF, if we ever use that for SS14). That said, I'm neither an admin that would have to use this feature, nor a maintainer that would have to maintain it, so I don't really care about this enough to go to war about it.

**Comment by Pangogie** [comment]
We should examine this list again and check things off.

**Comment by ike709** [comment]
Job bans are in: https://github.com/space-wizards/space-station-14/pull/6703

**Comment by ike709** [comment]
Adjusting the number of job slots is also in.

**Comment by ike709** [comment]
Decent admin logging is also in.

**Comment by Peptide90** [comment]
New compendium of requests and things we should have for 2022 since this issue is old:

### Important

- [ ] Auto Moderator - Essentially a chat filter that we can feed specific words and will auto ban or log accounts.
- [ ] #8553
**Logs**
- [ ] Admin Logs for crayons, paper and other interactive media
- [ ] Logs for cuffing people
- [ ] Logs accessible per entity - see who interactived with it.
- [ ] Chat Notifications for griefing behaviour - how it is in SS13, get a notification with the name and a teleport button to go to explosions, people setting AME or PA high etc.
- [ ] #7212
- [ ] #7173
- [ ] Logs for cutting wires? Maybe more specifically MV and HV or when doing a spree of LV.

### Other / Wishlist

- [ ] #7981
- [ ] Search bar in admin menu players tab (like there is in the teleport tab)
- [ ] Player Notes button in admin menu doesn't do anything.
- [ ] Should be able to apply notes to people offline and access notes via the ban panel online.

**Comment by Mirino97** [comment]
@Peptide90 with the merging of #10268, mind ticking the following items?
- Admin Logs for crayons (#10268)
- Logs for cuffing people (#10268)
- Logs for cutting wires (#10268)
- Both #7212 #7173 entries

- Admin notes for offline players #10292

**Comment by ShadowCommander** [comment]
Boxes have been checked.

**Comment by ike709** [comment]
Role timers needs to be ticked too @ShadowCommander

**Comment by IProduceWidgets** [comment]
Almost everything in here has been done (at in some basic respect) except for Automated Chat Moderator / Filters.

Shmaybe at some point someone wants to move some of these things into a snazy UI as opposed to the various places the information is currently available, but I would argue that's outside the scope of the issue as is.

**Comment by SlamBamActionman** [comment]
This issue would benefit from being split up into multiple issues, to make it easier for contributors to process them.

In the future use https://github.com/orgs/space-wizards/projects/8

**Comment by Peptide90** [comment]
This ancient issue lives to fight another day 😁
