### ISSUE TITLE
[ATMOS] devices/piping/pipe tracker

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#4203]
TO-DO:
- [x] Mapping (#4909)
    - [x] Atmospherics Department
    - [x] PipeNet
- [x] Pipes
    - [x] Behavior
    - [x] #4393
    - [x] #4404
    - [x] #4261
    - [x] Come up with better way to update device appearance.
    - [x] Anchoring/Unanchoring
    - [x] Unsafe unanchoring
        - [ ] Yeet person backwards
    - [x] #4921 
    - [x] #5020
- [ ] Easy Construction
    - [ ] RPD
    - [ ] Admin Tool that's literally the RPD but more advanced?
- [ ] Atmos Devices
    - [x] Sane update logic
    - [x] #4405
    - [x] Anchoring/Unanchoring
    - [x] Subfloor rendering
    - [x] Unary Devices
        - [x] Outlet Injector (#8963)
            - [x] Behavior
            - [x] UI
            - [x] Appearance
        - [x] Portables Connector (Tank port, etc)
            - [x] Behavior
        - [x] Passive Vent
            - [x] Behavior
            - [x] Appearance
        - [x] Vent Pump
            - [x] Behavior
            - [x] Appearance
            - [x] UI (via air alarm)
        - [x] Vent Scrubber
            - [x] Behavior
            - [x] Appearance
            - [x] UI (via air alarm)
        - [X] Thermomachine
            - [x] Behavior
            - [x] Appearance            
            - [X] Construction (#6803)
            - [X] UI (#6833)
    - [ ] Binary Devices
        - [ ] Circulator
            - [ ] Behavior
            - [ ] Appearance
        - [ ] Passive Gate
            - [x] Behavior
            - [ ] Interaction (toggle)
            - [ ] Appearance (toggle)
        - [x] Pressure Pump
            - [x] Behavior
            - [x] Appearance
            - [x] UI
        - [X] Volume Pump
            - [x] Behavior
            - [X] Appearance
            - [x] UI
        - [x] Valve
            - [x] Behavior
            - [x] ECS
            - [x] Appearance
        - [x] Dual-port Vent Pump
            - [x] Behavior (#4270)
            - [x] Appearance
            - [x] UI (using multitool for now) 
    - [x] Trinary Devices
        - [x] Filter
            - [x] Behavior
            - [x] Appearance
            - [x] UI
        - [x] Mixer
            - [x] Behavior
            - [x] Appearance
            - [x] UI
    - [ ] Other Devices
        - [x] #5018
        - [ ] Meter
            - [ ] Behavior
            - [ ] Appearance
            - [ ] Construction
        - [ ] Gas Miner
            - [x] Behavior
            - [ ] Power Usage
            - [ ] Appearance
- [x] Gas Canister Rework
    - [x] Behavior
    - [x] Connecting to Ports
    - [x] Inserting Gas Tanks
    - [x] Removing inserted Gas Tank
    - [x] Release gas into atmosphere
    - [x] Make canisters not use a passive gate, instead use gas mixture "release gas to"...
    - [x] Appearence
        - [x] Pressure meter
        - [x] Connected to port
        - [x] Inserted tank
    - [x] UI
      - [x] #4267
    - [x] #4207

**Comment by Efruit** [comment]
## [From /vg/](https://ss13.moe/wiki/index.php/Atmospherics_objects)
_(N.B. This is just an index of differences, not necessarily a checklist of things to build.)_

### Tools
- [ ] Socket wrench
  - [ ] Atmos devices/pipes locking out standard wrenches when overpressured
- [ ] Atmos analyzer
  - [ ] Open areas
  - [ ] Pipes and devices
- [ ] T-Ray Scanner (Shows subfloor; #4830)

-----

### Machines
- [ ] Pipe Dispenser
  - [ ] Disposal Pipe Dispenser
- [ ] Atmospheric Automation Console
- [ ] Atmos Alerts Console
- [ ] Atmos Control Console

-----

### Piped Devices
- [ ] Pipe Layering
  - [ ] Layer Adapters
  - [ ] Pipe Manifold
- [ ] [Heat Exchange Pipes](https://ss13.moe/wiki/index.php/Guide_to_Atmospherics#Heat_Exchange)
  - [ ] Junction
  - [ ] Pipes
  - [ ] Manifolds
  - [ ] Thermal Plate
- [ ] Gas Tanks
  - [ ] MSGS
 - [ ] Digital Valves
 - [ ] T-Valves
   - [ ] Manual
   - [ ] Digital
- [ ] Injector
- [ ] Heat Exchanger (not the same as the HE pipes above)

-----

### Portable
- [ ] Space Heater
- [ ] Portable Pump
- [ ] Portable Scrubber

-----

##### Arguable
- [ ] Disposal Outlet
- [ ] Disposal Intake
- [ ] Transit Tubes

**Comment by ike709** [comment]
Mixer UI is now in.

**Comment by mirrorcult** [comment]
this is basically done

**Comment by mirrorcult** [comment]
(or has other issues open already)
