### ISSUE TITLE
Body-related refactor overview

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4394]
## Description

Little tracker for things that need to be done for a BodySystem refactor

- [x] Damageable refactor #3882 
- [x] Rework metabolism #4395 #5246 #5157
- [x] Turn mechanismbehaviors into components #5630 #5281 #5249 #5248
- [x] #5151
- [x] Rework respiration #6022  #5603 
- [x] ECS bobby #6147 #5632 #5629 #6023 #10278 #11991
- [x] ECS/rework MobState for dynamic thresholds #13389 
- [ ] Per-limb damage #13917
- [x] Blood/reagentdata
- [ ] Health doll/targeting rework
- [ ] Organ damage
- [ ] Surgery #3939 
- [ ] Tests/docs

**Comment by mirrorcult** [comment]
- [ ] Reagent / bartending rework? https://discord.com/channels/310555209753690112/770682801607278632/870667487627313242

**Comment by DrSmugleaf** [comment]
> * [ ]  Bidirectional destructible thresholds [@Ygg01]

The point of these in the end is to enable a sane way of making damage **_and healing_** change the sprite of an entity, for example for windows and body parts.

**Comment by DrSmugleaf** [comment]
> * [ ]  Rethink mechanisms; possibly replace with just components [@mirrorcult]
> * [ ]  ECS

If these two are done then mechanism behavior execution order can be defined by using UpdatesBefore and UpdatesAfter in the respective entity systems.

**Comment by mirrorcult** [comment]
> > * [ ]  Rethink mechanisms; possibly replace with just components [@mirrorcult]
> > * [ ]  ECS
> 
> If these two are done then mechanism behavior execution order can be defined by using UpdatesBefore and UpdatesAfter in the respective entity systems.
> 

true, that would be best; then BodySystem itself can just handle adding and removing organs

**Comment by deltanedas** [comment]
i have amputation working so far in surgery using #13917, will open pr when wounds pr is mostly finished

**Comment by mirrorcult** [comment]
pretty much all of this is done or is in other issues
