### ISSUE TITLE
Big ol' Solution Meta issue

### ISSUE THREAD

**Issue by Ygg01** [space-wizards/space-station-14#4690]
## Description
Ok, so `SolutionContainerManagerComponent` has been added but it's not the end of Solution-related refactors.

Feel free to add your grievances:

- [x] #5078
- [X] Add default solution name
- [x] #4547  
- [x] #3926 
- [ ] #4534 
~~- [ ] `SolutionContainerSystem` should take care of Solutions as well. (and be renamed)~~
- [ ] `FitsInDispenser` seems like it should be a tag that just looks for `DrawableComponent`
- [ ] `RefillableComponent` could add some sounds and completely replace `FireExtinguisherComponent`
- [x] #5083 Methods on Solution-related systems should use `EntityUid` instead of `IEntity` but offer `IEntity` params as a convenience. 
~~- [ ] Investigate removing `ReagentUnit` non-ReagentUnit equality comparisson.~~
~~- [ ] Many methods that take `(string id, ReagentUnit quant)` can be replaced with `ReagentQuantity`~~

**Comment by 20kdc** [comment]
For some reason, every single thing on Saltern that has a solution container ends up writing it into the blueprint, empty.
I suspect this is why the plasma items are "empty".

**Comment by Ygg01** [comment]
> For some reason, every single thing on Saltern that has a solution container ends up writing it into the blueprint, empty.
> I suspect this is why the plasma items are "empty".

It might be a serialization issue, I was going to investigate but I'm not feeling well. 

One way to fix it is to enter default values for maxVol on every `solution container` and  fix values on `saltern.yml`, either manually or via save/load.

That said it's not a true fix. Moment someone maps a SolutionContainer twith slightly different values than default it's going to resurface again.

**Comment by 20kdc** [comment]
as far as I can tell the serialization issue is that DataField is writing tons of data to the blueprint it shouldn't, and this applies across several systems
Applying `readOnly` to everything *may* be an actual fix to some extent

**Comment by Ygg01** [comment]
> as far as I can tell the serialization issue is that DataField is writing tons of data to the blueprint it shouldn't, and this applies across several systems

Well from what I saw,  spawning does it's job. On save the entity is minimized and only fields differing from default are saved in the map. 

However on load rather than taking value from prototype and applying diff, the load overrides the value.

**Comment by 20kdc** [comment]
Not sure how this is an on-load issue:
+ there shouldn't be a value in the map in the first place
+ when I removed the component overrides from the map, they got put back in again on save
+ The corrected map without a further save works properly (map-placed plasma actually contains plasma, etc.)

**Comment by Ygg01** [comment]
>     * there shouldn't be a value in the map in the first place
Yes, it should. On init of `SolutionContainer` if `Sum(ReagentUnit)` is greater than the `maxVol`, `maxVol` is set to `Sum(ReagentUnit)`. Is this a bug? No. It's not different from someone going and manually changing some reagent values.

>     * when I removed the component overrides from the map, they got put back in again on save
The component overrides aren't the problem; it's an inconsistency between saving and load. In other words, a serialization issue. 
If `something != deserialize(serialize(something))` 

>     * The corrected map without a further save works properly (map-placed plasma actually contains plasma, etc.)
Did you fix `maxVol` on solution prototype?

This talk should have been on Discord, I repeated this same talk like 3 different times there and here already.

**Comment by 20kdc** [comment]
I said it wasn't an on-load issue, not that it wasn't an on-save issue.

**Comment by 20kdc** [comment]
Oh, wait, I think I get what you're saying - is the maxVol in the prototype different to what gets loaded because of internal changes? Because in that case it's *still* going to cause issues, because even with perfect serialization it'll be writing in data that, when the prototype changes, will still overwrite things.

**Comment by Ygg01** [comment]
> Oh, wait, I think I get what you're saying - is the maxVol in the prototype different to what gets loaded because of internal changes? Because in that case it's still going to cause issues, because even with perfect serialization it'll be writing in data that

Well, partially, here is the gist of it:

prototype for `WeldingTank`
```yaml
- type: solutionContainer
  solutions:
     tank:
        reagents:  
        - id: WeldingFuel
          quantity: 1500
```

on spawn becomes:

```yaml
- type: solutionContainer
  solutions:
     tank:
        maxVol: 1500 #Added by system
        reagents:  
        - id: WeldingFuel
          quantity: 1500
```

what's saved in the `saltern.yaml` (the diff between prototype and entity)

```yaml
- type: solutionContainer
  solutions:
     tank:
        maxVol: 1500 #Saved 
```

What's loaded on map start:

```yaml
- type: solutionContainer
  solutions:
     tank:
        maxVol: 1500 #Saved 
```

Rather than taking prototype entity and finding a tank entry and changing its field. The load bulldozes over the values.

**Comment by mirrorcult** [comment]
@Ygg01 is right, this is a serialization issue, serv3 doesn't handle merging dictionaries and in this case it.. doesnt really handle merging 'solutions' either, i'm not really sure how you would do this

honestly it should probably just not serialize the maxvol

**Comment by Ygg01** [comment]
> @Ygg01 is right, this is a serialization issue, serv3 doesn't handle merging dictionaries and in this case it.. doesnt really handle merging 'solutions' either, i'm not really sure how you would do this

Couldn't we load prototype values and first check for values before overriding them?

**Comment by 20kdc** [comment]
The problem I see is that even assuming that the issue with the loading is fixed,
if the `WeldingTank` prototype is later changed to, say, contain only 1000u, the `maxVol` will still be in the map and will cause the welding tank to gain additional volume it shouldn't have. This is, to be clear, even *if* the serialization problem is fixed.

**Comment by PaulRitter** [comment]
> > as far as I can tell the serialization issue is that DataField is writing tons of data to the blueprint it shouldn't, and this applies across several systems
> 
> Well from what I saw, spawning does it's job. On save the entity is minimized and only fields differing from default are saved in the map.
> 
> However on load rather than taking value from prototype and applying diff, the load overrides the value with whatever is saved in the map (i.e `saltern.yml`).
> 
> In other words it's a serialization issue not a solution issue. Solution seems to be one of few things with nested dictionary.

this is intended behaviour. HOWEVER _this may or may not be the one BIG issue i still have with serv3, it never being implemented properly._ More specifically, serv3 currently only has very hacky and limited ability to define custom merging logic, which this is suffering from. This, as well as the fact that computed default values (TODO!) aren't supported, makes this a serv3 issue. I'm gonna open two issues related to this.
