### ISSUE TITLE
[TRACKER] Construction Graph Language 2

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/space-station-14#5048]
This is a tracker for everything planned for ConstructionGL2

-- PART 1 -- #5017 
- [x] ECS Construction.
- [x] Construction logic rewritten entirely.
- [x] Construction Steps can handle arbitrary Directed Events.
- [x] Construction no longer uses `async`.
- [x] Construction event handling is queued and handled in `Update`.
- [x] Conditions and actions use `EntityUid` and `IEntityManager`.
- [x] Remove Nested Steps.

-- PART 2 --  #5103 
- [x] Construction Guided Steps Refactor
    - [x] Server generates guided steps, client just displays them.
    - [x] Conditions show up in guided steps for certain steps.

-- TODO --
- [ ] ~~Cross-graph edges~~ Overly complex for no good reason
- [ ] RaiseAttemptEvent condition
- [ ] Initial Construction Refactor
    - [ ] Use dummy entities for this?
    - [ ] #11374
- [ ] Add New Construction Graph Steps.
    - [ ] Step for empty hand interaction.
    - [ ] Step for inserting item in an entity whitelist.
    - [ ] Investigate re-adding Nested Steps with their own component for this. (would be more maintainable)
- [ ] Cooking Construction Graphs (will need severe ideaguy-ing) #3409
- [ ] Step-specific Conditions.
- [ ] Make examine guided steps fancier.
- [ ] Support multiple identical steps, use some UI to select which path to take.
- [ ] #3357
- [ ] Documentation
    - [ ] Document how to add new steps.
    - [ ] Improve construction doc by splitting it into multiple pages.

**Comment by AJCM-git** [comment]
Should probably add these to the TODO #2922  #3316

**Comment by Zumorica** [comment]
> Should probably add these to the TODO #2922 #3316

#3316 is not really something we want, and #2922 is part of ` Make examine guided steps fancier.` already
