### ISSUE TITLE
Moony's Todo Commands Checklist

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5346]
## Description
just a bunch of shit i'll probably implement. feel free to steal from the list and do it yourself, I provide no guarantees i'll finish these (or they may end up obsoleted before I even code them).
- [ ] `rename <id> <name>`
Renames an entity
- [ ] `quickrename <id>`
Renames an entity using the random name generator, with the appropriate gender.
- [ ] `makewanderai <id>`
Sets up an entity with a UtilityAI and required components, and makes it wander around like most passive mobs.
- [ ] `makeassaultai <id>`
Sets up an entity with a UtilityAI and the required components, and makes it attack nearby people, ala space carp.
- [ ] `addtag <id> <tag>`
Adds a tag to an entity.
- [ ] `rmtag <id> <tag>`
Removes a tag from an entity.
- [ ] `spawntagged <prototype> <x> <y> <tag> OR <prototype> <id> <tag> OR <prototype> <tag>`
Spawns an entity, but with a given tag.
- [ ] `spawninhand <prototype> <id> [force]`
Spawns an entity into the given entity's hands, if possible (otherwise drops it on the ground, unless forced, in which case it'll give the entity an extra hand to be able to fit it.)
- [ ] `pinball <id>`
Makes all Hard fixtures on an entity have a restitution of 1.2, mass of 0, Dynamic, and InAir.

## fucking around
Summon a murder of angry clowns. With bats.
```
forall with Body do spawntagged MobHuman $ID admintag1
forall with Body tagged admintag1 do quickrename $ID; setoutfit $ID ClownGear; makeassaultai $ID; rmtag admintag1; spawninhand BaseBallBat $ID
```

**Comment by mirrorcult** [comment]
needs specific issues not super actionable rn (or already basically done)

**Comment by moonheart08** [comment]
> needs specific issues not super actionable rn (or already basically done)

oh god this is ANCIENT how did you even find this.

(most of this is completely inactionable yes)

**Comment by ShadowCommander** [comment]
> > needs specific issues not super actionable rn (or already basically done)
> 
> oh god this is ANCIENT how did you even find this.
> 
> (most of this is completely inactionable yes)

We're clearing out issues, so all the old ones are getting closed or commented on.
