### ISSUE TITLE
Multi-station checklist

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5683]
Lot of shit needs done for fully viable multi-station

- [ ] Per-station announcements (You don't need to announce to every station around that your captain likes beans, unless you really want to.)
- [ ] Per-station comms 
- [ ] Per-station cloning fixup
- [x] Per-station cargo fixup
- [ ] Per-station alerts
- [ ] Per-station events (Partially done to make rads, gas leak, and kudzu not break)
- [ ] Per-station R&D tech pools (for when you don't want the clown ship researching anything except new prank methods)
- [ ] Per-station access
- [x] Per-station jobs

**Comment by Efruit** [comment]
- [ ] Per-station access
