### ISSUE TITLE
Map renderer TODO list

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#6062]
Merged in https://github.com/space-wizards/space-station-14/pull/3613

- [ ] Making it run ~in 40 milliseconds~ faster (it takes me 35 seconds to run it locally, 2 minutes in CI and it only does one map file at a time for example).
- [x] Icon smoothing.
- [x] Layer direction.
- [ ] RSI delays and animations.
- [ ] Adding support for selectively rendering entities (including/excluding wires, including container contents).
- [ ] Separating these different versions of the map into different images.
- [x] Hiding the dummy client entity.
- [x] Removing the submodule update.
- [ ] Make it take entities into account for image bounds, not just the grid box.
- [ ] Test with multiple grids.
- [x] Pinging PJB to edit the repo's environment variables to add a github token so we can have the action directly commit instead of opening a PR.
- [x] PJB doing the thing.
- [ ] ~~Make it use os mesa and llvmpipe for off screen rendering. (when PJB compiles it)~~
- [ ] Properly rendering entities that aren't 32x32

**Comment by mirrorcult** [comment]
it works with multiple grids btw
