### ISSUE TITLE
Wizard to-do list

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#9072]
## Description

Everything that should at-minimum be done for wiz gamerule

More spells (the basics):
- [x] Knock
- [x] Blink
- [x] Summon [whatever]  
- [x] Fireball #9058 
- [x] Smite #9060 
- [x] Staves/wands #9070 
  - [x] Polymorph (specific)
  - [x] Fireball
  - [x] Death
  - [x] Healing
  - [x] Door
  - [x] Animation
  - [ ] Change (wabbajack)
  - [ ] Chaos (any of the above)
- [x] Mindswap
- [ ] Magic missile
- [x] Ethereal jaunt

Basic items:
- [x] Scrying orb
- [x] Wiz holopara (djinn) (this is like basically already done apparently)

Basics of wiz gameplay:
- [x] Mind-inherent spells (requires mind entity refactor, which is being done)
- [x] Spellbook purchasing spells
- [x] Wiz shuttle
- [x] Wiz gamerule

**Comment by keronshb** [comment]
I had this up at one point: https://hackmd.io/JJrWmEL-RJWb8waOXQY6zw

All seems to align basically. We're getting super close to wiz!

**Comment by Emisse** [comment]
we have shuttle and keronsh is working on gamerule/shop

**Comment by K-Dynamic** [comment]
Can be closed? We've had the wizard for a few months now
